packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"
  - "functions/*"
  - "infra"
  - "!scripts"
  - '!out/**'

# TODO add these into each package.json
catalog:
  typescript: ^5.3.3
  eslint: ^9.11.0
  "@swc/cli": ^0.3.14

catalogs:
  drizzle:
    drizzle-kit: ^0.22.8
    drizzle-orm: ^0.33.0
