packages:
  - "apps/*"
  - "libs/**/*"
  - "tooling/*"
  - "functions/**/*"
  - "infra"
  - "!out/**"

catalogs:
  eslint9: 
    eslint: ^9.15.0

  typescript5:
    typescript: ^5.7.2

  graphql:
    graphql: ^16.10.0