packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"
  - "functions/*"
  - "infra"
  - "!scripts"
  - '!out/**'

# TODO add these into each package.json
catalog:
  typescript: ^5.3.3
  eslint: ^9.11.0