name: infra
main: index.ts
description: AWS IaC
runtime:
  name: nodejs
  options:
    packagemanager: pnpm
config:
  infra:backendPort:
    type: integer
    description: The port of the backend
  infra:dbName:
    type: string
    description: The name of the database
  infra:dbPassword:
    type: string
    description: The password of the database
  infra:dbPort:
    type: integer
    description: The port of the database
  infra:dbUser:
    type: string
    description: The user of the database
  pulumi:tags:
    value: 
      pulumi:template: aws-typescript
