name: Mobile Bug Report
description: Report a bug in our mobile app (iOS/Android)
title: "[BUG]: "
labels: ["bug", "mobile", "triage"]
assignees:
  - lbxa
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! The more information you provide, the better we can help.
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you experiencing the issue on?
      options:
        - iOS
        - Android
        - Both
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device Details
      description: What device are you using? (e.g., iPhone 14 Pro, Samsung Galaxy S23)
      placeholder: iPhone 14 Pro
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What OS version is your device running?
      placeholder: iOS 17.2 / Android 14
    validations:
      required: true
  - type: dropdown
    id: app-version
    attributes:
      label: App Version
      description: What version of our app are you running? (Check Settings > About)
      options:
        - 1.0.2 (Current Release)
        - 1.0.3 (Beta)
      default: 0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Describe the bug and include:
        - What were you trying to do?
        - What did you expect to happen?
        - What actually happened?
        - Steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Tap on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Screen Recording
      description: If applicable, add screenshots or screen recordings to help explain your problem
      placeholder: Drag and drop images/videos here
  - type: textarea
    id: crash-logs
    attributes:
      label: Crash Logs
      description: If the app crashed, please provide the crash logs if available
      render: shell
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: email@example.com
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
