name: Setup Monorepo
description: Prepare and install everything for the monorepo

inputs:
  node-version:
    description: Version of Node to use
    default: 20.x

  eas-version:
    description: Version of EAS CLI to use
    default: latest

  expo-token:
    description: Expo token to authenticate with
    required: false

runs:
  using: composite
  steps:
    - name: 🏗 Setup repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Extract pnpm version
      id: extract_pnpm_version
      run: |
        # Extract the pnpm version from package.json
        pnpm_version=$(jq -r '.packageManager | select(startswith("pnpm@")) | split("@")[1]' package.json)
        echo "pnpm-version=$pnpm_version" >> $GITHUB_ENV
      shell: bash

    - name: 🏗 Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ env.pnpm-version }}

    - name: 🏗 Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: 🏗 Setup Expo
      uses: expo/expo-github-action@v8
      with:
        eas-version: ${{ inputs.eas-version }}
        token: ${{ inputs.expo-token }}

    - name: 📦 Install dependencies
      run: pnpm install
      shell: bash

    # TODO understand how this can be used
    # - name: 💾 Restore cache
    #   uses: actions/cache@v4
    #   with:
    #     key: turbo-${{ runner.os }}-${{ github.sha }}
    #     restore-keys: |
    #       turbo-${{ runner.os }}
    #     path: |
    #       node_modules/.cache/turbo
    #       apps/*/.turbo
    #       libs/*/.turbo
    #       functions/*/.turbo