export { default as AppIconsSvg } from "../assets/icons/app-icons.svg";
export { default as AppStoreSvg } from "../assets/icons/app-store.svg";
export { default as BoltSvg } from "../assets/icons/bolt.svg";
export { default as ChartSvg } from "../assets/icons/chart.svg";
export { default as CheckSvg } from "../assets/icons/check.svg";
export { default as DumbbellSvg } from "../assets/icons/dumbbell.svg";
export { default as GroupSvg } from "../assets/icons/group.svg";
export { default as MinusSvg } from "../assets/icons/minus.svg";
export { default as OnexSvg } from "../assets/icons/onex.svg";
export { default as PlusSvg } from "../assets/icons/plus.svg";
export { default as RankingsSvg } from "../assets/icons/rankings.svg";
export * from "./svg";
