name: Check PR title  
  
on:  
  pull_request:  
    types: [opened, edited, synchronize, labeled, unlabeled]  
  
jobs:  
  check-title:  
    runs-on: ubuntu-latest  
  
    steps:  
    - name: Check PR title for Conventional Commits format  
      uses: actions/github-script@v4  
      with:  
        script: |  
          const prTitle = context.payload.pull_request.title;  
          const conventionalCommitPattern = /^(feat|fix|perf|docs|style|refactor|test|chore)(\/[a-zA-Z0-9_-]+)?: .+$/;  
  
          if (!conventionalCommitPattern.test(prTitle)) {  
            core.setFailed(`The PR title "${prTitle}" does not follow Conventional Commits format.`);  
          }  